
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>((localStorage.getItem("language") as Language) || "en");

  const t = (key: string) => {
    return translations[language][key] || translations["en"][key] || key;
  };

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

const translations = {
  en: {
    appName: "Deducto",
    welcome: "Welcome",
    login: "Login",
    logout: "Logout",
    register: "Register",
    dashboard: "Dashboard",
    categories: "Categories",
    notFound: "404 Not Found",
    pageNotFound: "Page not found",
    goHome: "Go Home",
    loading: "Loading...",
    addNewExpense: "Add New Expense",
    description: "Description",
    amount: "Amount",
    category: "Category",
    date: "Date",
    quantity: "Quantity",
    addExpense: "Add Expense",
    editExpense: "Edit Expense",
    updateExpense: "Update Expense",
    deleteExpense: "Delete Expense",
    cancel: "Cancel",
    recentExpenses: "Recent Expenses",
    noExpenses: "No expenses recorded",
    total: "Total",
    allCategories: "All Categories",
    filterByCategory: "Filter by Category",
    qty: "Qty",
    name: "Name",
    addCategory: "Add Category",
    addNewCategory: "Add New Category",
    categoryName: "Category Name",
    enterCategoryName: "Enter category name",
    addingCategory: "Adding...",
    manageCategories: "Manage Categories",
    loadingCategories: "Loading categories...",
    noCategories: "No categories yet",
    deleteCategory: "Delete Category",
    editCategory: "Edit Category",
    updateCategory: "Update Category",
    categoryAdded: "Category Added",
    categorySuccessfullyAdded: "Your category has been successfully added",
    categoryDeleted: "Category Deleted",
    categorySuccessfullyDeleted: "The category has been successfully deleted",
    errorFetchingCategories: "Error Fetching Categories",
    errorAddingCategory: "Error Adding Category",
    errorDeletingCategory: "Error Deleting Category",
    expensesByCategory: "Expenses by Category",
    noExpensesToDisplay: "No expenses to display",
    uncategorized: "Uncategorized",
    allTime: "All Time",
    today: "Today",
    thisWeek: "This Week",
    thisMonth: "This Month",
    previous7Days: "Last 7 Days",
    previous30Days: "Last 30 Days",
    customDateRange: "Custom Date Range",
    expenseAdded: "Expense Added",
    expenseSuccessfullyRecorded: "Expense successfully recorded",
    errorAddingExpense: "Error Adding Expense",
    whatExpenseFor: "What is this expense for?",
    selectCategory: "Select a category",
    loadingCategoriesEllipsis: "Loading categories...",
    adding: "Adding...",
    count: "Count",
    signIn: "Sign In",
    signUp: "Sign Up",
    email: "Email",
    password: "Password",
    signingIn: "Signing In...",
    signingUp: "Signing Up...",
    trackExpenses: "Track and manage your expenses",
    resetPassword: "Reset Password",
    resetPasswordDescription: "Enter your email to receive a password reset link",
    sendResetLink: "Send Reset Link",
    sendingResetLink: "Sending...",
    resetEmailSent: "Reset Email Sent",
    checkYourEmail: "Please check your email for the reset link",
    resetLinkSent: "A password reset link has been sent to your email",
    sendAnotherLink: "Send Another Link",
    resetError: "Reset Error",
    updatePassword: "Update Password",
    createNewPassword: "Create a new password for your account",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    passwordsDoNotMatch: "Passwords do not match",
    updatingPassword: "Updating...",
    passwordUpdated: "Password Updated",
    passwordUpdateSuccess: "Your password has been successfully updated",
    updatePasswordError: "Error Updating Password",
    forgotPassword: "Forgot password?",
    confirmDelete: "Confirm Deletion",
    deleteExpenseMessage: "Are you sure you want to delete this expense? This action cannot be undone.",
    delete: "Delete",
    deleting: "Deleting...",
    expenseDeleted: "Expense Deleted",
    expenseDeletedMessage: "The expense has been successfully deleted.",
    errorDeletingExpense: "Error Deleting Expense",
    importExport: "Import/Export",
    dataImportExport: "Data Import/Export",
    exportImportDescription: "Export your data for backup or import previously exported data.",
    exportData: "Export Data",
    importData: "Import Data",
    closeDialog: "Cancel",
    exportSuccessful: "Export Successful",
    dataExportedToFile: "Your data has been exported to a file.",
    importSuccessful: "Import Successful",
    dataImportedSuccessfully: "Your data has been imported successfully.",
    importFailed: "Import Failed",
    invalidFileFormat: "The file format is invalid or corrupted.",
    errorReadingFile: "There was an error reading the file."
  },
  es: {
    appName: "Deducto",
    welcome: "Bienvenido",
    login: "Iniciar sesión",
    logout: "Cerrar sesión",
    register: "Registrarse",
    dashboard: "Panel de control",
    categories: "Categorías",
    notFound: "404 No encontrado",
    pageNotFound: "Página no encontrada",
    goHome: "Ir a la página principal",
    loading: "Cargando...",
    addNewExpense: "Agregar Nuevo Gasto",
    description: "Descripción",
    amount: "Cantidad",
    category: "Categoría",
    date: "Fecha",
    quantity: "Cantidad",
    addExpense: "Agregar Gasto",
    editExpense: "Editar Gasto",
    updateExpense: "Actualizar Gasto",
    deleteExpense: "Eliminar Gasto",
    cancel: "Cancelar",
    recentExpenses: "Gastos Recientes",
    noExpenses: "No hay gastos registrados",
    total: "Total",
    allCategories: "Todas las Categorías",
    filterByCategory: "Filtrar por Categoría",
    qty: "Cant",
    name: "Nombre",
    addCategory: "Agregar Categoría",
    addNewCategory: "Agregar Nueva Categoría",
    categoryName: "Nombre de Categoría",
    enterCategoryName: "Ingresar nombre de categoría",
    addingCategory: "Agregando...",
    manageCategories: "Administrar Categorías",
    loadingCategories: "Cargando categorías...",
    noCategories: "Aún no hay categorías",
    deleteCategory: "Eliminar Categoría",
    editCategory: "Editar Categoría",
    updateCategory: "Actualizar Categoría",
    categoryAdded: "Categoría Agregada",
    categorySuccessfullyAdded: "Tu categoría ha sido agregada exitosamente",
    categoryDeleted: "Categoría Eliminada",
    categorySuccessfullyDeleted: "La categoría ha sido eliminada exitosamente",
    errorFetchingCategories: "Error al Cargar Categorías",
    errorAddingCategory: "Error al Agregar Categoría",
    errorDeletingCategory: "Error al Eliminar Categoría",
    expensesByCategory: "Gastos por Categoría",
    noExpensesToDisplay: "No hay gastos para mostrar",
    uncategorized: "Sin categoría",
    allTime: "Todo el Tiempo",
    today: "Hoy",
    thisWeek: "Esta Semana",
    thisMonth: "Este Mes",
    previous7Days: "Últimos 7 Días",
    previous30Days: "Últimos 30 Días",
    customDateRange: "Rango de Fechas Personalizado",
    expenseAdded: "Gasto Agregado",
    expenseSuccessfullyRecorded: "Gasto registrado exitosamente",
    errorAddingExpense: "Error al Agregar Gasto",
    whatExpenseFor: "¿Para qué es este gasto?",
    selectCategory: "Seleccione una categoría",
    loadingCategoriesEllipsis: "Cargando categorías...",
    adding: "Agregando...",
    count: "Cantidad",
    signIn: "Iniciar Sesión",
    signUp: "Registrarse",
    email: "Correo Electrónico",
    password: "Contraseña",
    signingIn: "Iniciando Sesión...",
    signingUp: "Registrando...",
    trackExpenses: "Rastrea y administra tus gastos",
    resetPassword: "Restablecer Contraseña",
    resetPasswordDescription: "Ingrese su correo electrónico para recibir un enlace de restablecimiento de contraseña",
    sendResetLink: "Enviar Enlace",
    sendingResetLink: "Enviando...",
    resetEmailSent: "Correo Enviado",
    checkYourEmail: "Por favor, revise su correo electrónico para ver el enlace de restablecimiento",
    resetLinkSent: "Se ha enviado un enlace de restablecimiento de contraseña a su correo electrónico",
    sendAnotherLink: "Enviar Otro Enlace",
    resetError: "Error de Restablecimiento",
    updatePassword: "Actualizar Contraseña",
    createNewPassword: "Cree una nueva contraseña para su cuenta",
    newPassword: "Nueva Contraseña",
    confirmPassword: "Confirmar Contraseña",
    passwordsDoNotMatch: "Las contraseñas no coinciden",
    updatingPassword: "Actualizando...",
    passwordUpdated: "Contraseña Actualizada",
    passwordUpdateSuccess: "Su contraseña ha sido actualizada con éxito",
    updatePasswordError: "Error al Actualizar la Contraseña",
    forgotPassword: "¿Olvidó su contraseña?",
    confirmDelete: "Confirmar Eliminación",
    deleteExpenseMessage: "¿Estás seguro de que quieres eliminar este gasto? Esta acción no se puede deshacer.",
    delete: "Eliminar",
    deleting: "Eliminando...",
    expenseDeleted: "Gasto Eliminado",
    expenseDeletedMessage: "El gasto ha sido eliminado con éxito.",
    errorDeletingExpense: "Error al Eliminar el Gasto",
    importExport: "Importar/Exportar",
    dataImportExport: "Importar/Exportar Datos",
    exportImportDescription: "Exporta tus datos para respaldo o importa datos previamente exportados.",
    exportData: "Exportar Datos",
    importData: "Importar Datos",
    closeDialog: "Cancelar",
    exportSuccessful: "Exportación Exitosa",
    dataExportedToFile: "Tus datos han sido exportados a un archivo.",
    importSuccessful: "Importación Exitosa",
    dataImportedSuccessfully: "Tus datos han sido importados con éxito.",
    importFailed: "Fallo en la Importación",
    invalidFileFormat: "El formato del archivo es inválido o está corrupto.",
    errorReadingFile: "Hubo un error al leer el archivo."
  }
};
