// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kungeoclawmjxukemrqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1bmdlb2NsYXdtanh1a2VtcnFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODQzMzcsImV4cCI6MjA1OTQ2MDMzN30.OjB_VGNx_pTe_uRRL_51gGcNfp_op5d2mbYVOAjRrrU";

// Flag to indicate if we're using template credentials
export const isUsingTemplateCredentials = false;

// Production check
const isProduction = typeof import.meta !== 'undefined' && 
  typeof import.meta.env !== 'undefined' && 
  import.meta.env.MODE === 'production';

// Show warning or throw error if using template credentials
if (isUsingTemplateCredentials) {
  if (isProduction) {
    throw new Error('Cannot use template Supabase credentials in production. Please configure real credentials in config.json.');
  } else {
    console.warn('Using template Supabase credentials. Replace with real credentials in config.json for full functionality.');
  }
}

// Import the supabase client like this:
// import { supabase, isUsingTemplateCredentials } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
